"""update_employee_department_models_phase2

Revision ID: da7122b9e0e0
Revises: fd8002527a35
Create Date: 2026-06-29 11:20:17.856928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da7122b9e0e0'
down_revision: Union[str, None] = 'fd8002527a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('employees', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('shift_start_time', sa.String(length=5), nullable=True))
    op.add_column('employees', sa.Column('shift_end_time', sa.String(length=5), nullable=True))
    op.add_column('employees', sa.Column('photo_path', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('employees', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(length=254),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('employees', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'TERMINATED', name='employee_status'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint('employees_email_key', 'employees', type_='unique')
    op.drop_constraint('employees_employee_code_key', 'employees', type_='unique')
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.drop_column('employees', 'profile_image_path')
    op.drop_column('employees', 'work_shift_start')
    op.drop_column('employees', 'contact_number')
    op.drop_column('employees', 'work_shift_end')
    op.drop_column('employees', 'notes')
    op.drop_column('employees', 'registered_at')
    op.drop_column('employees', 'designation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('work_shift_end', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('contact_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('work_shift_start', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('profile_image_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.create_unique_constraint('employees_employee_code_key', 'employees', ['employee_code'])
    op.create_unique_constraint('employees_email_key', 'employees', ['email'])
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('employees', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'TERMINATED', name='employee_status'),
               existing_nullable=False)
    op.alter_column('employees', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=254),
               existing_nullable=True)
    op.alter_column('employees', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('employees', 'created_at')
    op.drop_column('employees', 'photo_path')
    op.drop_column('employees', 'shift_end_time')
    op.drop_column('employees', 'shift_start_time')
    op.drop_column('employees', 'phone')
    op.drop_column('employees', 'position')
    op.alter_column('departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
